### ISSUE TITLE
Alteracao na main

### ISSUE THREAD

**Issue by thiagooqueiroz** [dmfds/calculadorapolonesa#3]
Dennis , avisar a voce q retirei o corpo da main por que com switch acredito que ficaria invalido ...
 melhor trocar por uma seguencia de if e elses para um fgets para cada operador

**Comment by thiagooqueiroz** [comment]
ao visualizar favor fechar a issue

**Comment by dmfds** [comment]
Ok @thiagooqueiroz Vamos seguir essa linha de raciocínio.
